---
- name: Generate a secret pepper for NetBox if unspecified
  shell: "set -o pipefail; {{ netbox_python_binary }} {{ netbox_current_path }}/netbox/generate_secret_key.py\
          | tr -d $'\n' > {{ netbox_shared_path }}/generated_secret_pepper"
  args:
    creates: "{{ netbox_shared_path }}/generated_secret_pepper"
    executable: /bin/bash
  become: true
  become_user: "{{ netbox_user }}"

- name: Load saved secret pepper
  slurp:
    src: "{{ netbox_shared_path }}/generated_secret_pepper"
  register: _netbox_secret_pepper_file
